ai_goals:
- Read file sample.txt
- Send an analysis of the logical reasoning in a telegram message using the command telegram_message_user from the COMMMANDS list.
ai_name: LogicAnalyzer
ai_role: an AI designed to find the logical reasoning in local files of text
api_budget: 0.2