ai_goals:
- write a python function that takes a grid with h rows and w columns, where only
  one element is non-zero representing the position of piece, the function also takes
  a string representing a move of 1 up down left or right and return a the grid with
  the unit moved.
- Write another function that takes the width and height of the grid, starting position
  and destination position, initializes the grid and calls the move function multiple
  times until the piece reaches the destination printing the grid after each move
- write tests to make sure the piece has reached the destination
- counts how many moves were required
- starts again attemting to lower the number of moves required
ai_name: SimpleMoverAI
ai_role: an AI that will develop code to move a piece on a 2D grid of zeros where
  the location of the grid is set to 1 from starting position to destination
api_budget: 0.3
